defaults:
  - _self_
  - data: nerf_llff
  - network: nerf
  - train: nerf
  - rendering: nerf
  - encoding: positional
  - sampler: stratified_sampler
  - logs: default

cuda: 0
test: false
output: ./output

hydra:  
  output_subdir: null  
  run:  
    dir: ./logs