defaults:
  - _self_
  - data: nerf_llff
  - network: nerf
  - train: nerf
  - rendering: nerf
  - encoding: positional
  - sampler: stratified_sampler

cuda: 0
log: debug
test: false

hydra:  
  output_subdir: null  
  run:  
    dir: ./logsgit